version: '3.8'
services:
  compose:
    image: composer:latest
    command: "composer update"
    environment:
      REQUIRE_DEV: "true"
    volumes:
      - ./wbs:/var/www
    working_dir: "/var/www"
    init: true


  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    depends_on:
      - app

  app:
    build: .
    environment:
      APP_URL: http://app/
      DUSK_DRIVER_URL: http://selenium:4444/wd/hub
      APP_ENV: develop
      APP_KEY: base64:Y8ieBDrDoyvpfnsF5a/fI7xHvdPrReo7xPlojcyT1bQ=
      DB_CONNECTION: mysql
      DB_HOST: rdbms
      DB_DATABASE: forge
      DB_USERNAME: devel
      DB_PASSWORD: devel
      CACHE_DRIVER: redis
      REDIS_HOST: cache
      REDIS_PORT: 6379
    ports:
      - "80:80"
    volumes:
      - ./wbs:/var/www
    working_dir: "/var/www"
    depends_on:
      - rdbms
      - cache

  rdbms:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: devel
      MYSQL_PASSWORD: devel
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  cache:
    image: redis:latest

volumes:
  db-data:
